In [541]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
%matplotlib inline

import seaborn as sns
color = sns.color_palette()
sns.set_style('darkgrid')

from sklearn.preprocessing import normalize
from sklearn.linear_model import RidgeCV, LassoCV, LassoLarsCV

In [542]:
df = pd.read_csv("data/AmesHousing.csv")
# set the max columns to none
pd.set_option('display.max_columns', None)

# 1. Feature engineering

## 1.1 Exploration et Supression des colonnes inutiles

In [543]:
df.shape

(2930, 82)

In [544]:
df.sample(10)

,Order,PID,MS SubClass,MS Zoning,Lot Frontage,Lot Area,Street,Alley,Lot Shape,Land Contour,Utilities,Lot Config,Land Slope,Neighborhood,Condition 1,Condition 2,Bldg Type,House Style,Overall Qual,Overall Cond,Year Built,Year Remod/Add,Roof Style,Roof Matl,Exterior 1st,Exterior 2nd,Mas Vnr Type,Mas Vnr Area,Exter Qual,Exter Cond,Foundation,Bsmt Qual,Bsmt Cond,Bsmt Exposure,BsmtFin Type 1,BsmtFin SF 1,BsmtFin Type 2,BsmtFin SF 2,Bsmt Unf SF,Total Bsmt SF,Heating,Heating QC,Central Air,Electrical,1st Flr SF,2nd Flr SF,Low Qual Fin SF,Gr Liv Area,Bsmt Full Bath,Bsmt Half Bath,Full Bath,Half Bath,Bedroom AbvGr,Kitchen AbvGr,Kitchen Qual,TotRms AbvGrd,Functional,Fireplaces,Fireplace Qu,Garage Type,Garage Yr Blt,Garage Finish,Garage Cars,Garage Area,Garage Qual,Garage Cond,Paved Drive,Wood Deck SF,Open Porch SF,Enclosed Porch,3Ssn Porch,Screen Porch,Pool Area,Pool QC,Fence,Misc Feature,Misc Val,Mo Sold,Yr Sold,Sale Type,Sale Condition,SalePrice
2915,2916,923227100,20,RL,80.0,13384,Pave,NaN,Reg,Lvl,AllPub,Inside,Mod,Mitchel,Norm,Norm,1Fam,1Story,5,5,1969,1979,Gable,CompShg,Plywood,Plywood,BrkFace,194.0,TA,TA,PConc,TA,TA,Av,Rec,119.0,BLQ,344.0,641.0,1104.0,GasA,Fa,Y,SBrkr,1360,0,0,1360,1.0,0.0,1,0,3,1,TA,8,Typ,1,TA,Attchd,1969.0,RFn,1.0,336.0,TA,TA,Y,160,0,0,0,0,0,NaN,NaN,NaN,0,5,2006,WD,Normal,140000
2596,2597,535376090,20,RL,90.0,5400,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,OldTown,Norm,Norm,1Fam,1Story,5,7,1954,2000,Gable,CompShg,MetalSd,MetalSd,None,0.0,TA,Gd,CBlock,TA,TA,No,Rec,415.0,Unf,0.0,418.0,833.0,GasA,Ex,Y,SBrkr,833,0,0,833,0.0,0.0,1,0,2,1,Gd,4,Typ,0,NaN,Detchd,1955.0,Unf,1.0,326.0,TA,TA,Y,0,0,0,0,0,0,NaN,MnPrv,NaN,0,8,2006,WD,Normal,117000
2495,2496,532378130,20,RL,NaN,8020,Pave,NaN,IR1,Lvl,AllPub,Inside,Gtl,Sawyer,Norm,Norm,1Fam,1Story,5,6,1964,1964,Gable,CompShg,HdBoard,HdBoard,None,0.0,TA,TA,CBlock,TA,TA,No,ALQ,644.0,Unf,0.0,268.0,912.0,GasA,TA,N,SBrkr,912,0,0,912,0.0,0.0,1,0,3,1,TA,6,Typ,0,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,Y,0,0,0,0,0,0,NaN,GdWo,NaN,0,4,2006,WD,Normal,124000
2141,2142,907203110,20,RL,120.0,10356,Pave,NaN,Reg,Lvl,AllPub,Corner,Gtl,CollgCr,Norm,Norm,1Fam,1Story,5,6,1975,1975,Gable,CompShg,HdBoard,HdBoard,None,0.0,TA,TA,CBlock,TA,TA,Av,BLQ,716.0,Unf,0.0,253.0,969.0,GasA,TA,Y,SBrkr,969,0,0,969,0.0,0.0,1,1,3,1,TA,5,Typ,0,NaN,Attchd,1975.0,Unf,2.0,440.0,TA,TA,Y,0,0,0,0,0,0,NaN,MnPrv,NaN,0,1,2007,WD,Normal,122000
608,609,534402140,20,RL,NaN,11000,Pave,NaN,IR1,Lvl,AllPub,CulDSac,Gtl,NAmes,Norm,Norm,1Fam,1Story,5,6,1966,1966,Gable,CompShg,Plywood,Plywood,BrkFace,200.0,TA,TA,CBlock,TA,TA,Mn,BLQ,740.0,Rec,230.0,184.0,1154.0,GasA,Ex,Y,SBrkr,1154,0,0,1154,0.0,0.0,1,1,3,1,TA,6,Typ,1,Po,Attchd,1966.0,RFn,2.0,480.0,TA,TA,Y,0,58,0,0,0,0,NaN,MnPrv,NaN,0,11,2009,WD,Normal,154000
2493,2494,532378050,20,RL,NaN,13052,Pave,NaN,IR1,Lvl,AllPub,CulDSac,Gtl,Sawyer,Norm,Norm,1Fam,1Story,5,6,1965,1965,Gable,CompShg,HdBoard,HdBoard,None,0.0,TA,TA,CBlock,TA,TA,No,Rec,712.0,Unf,0.0,312.0,1024.0,GasA,TA,Y,SBrkr,1024,0,0,1024,0.0,0.0,1,1,3,1,TA,5,Typ,0,NaN,Attchd,1965.0,Unf,1.0,308.0,TA,TA,Y,0,0,0,0,0,0,NaN,MnPrv,NaN,0,1,2006,WD,Normal,120875
147,148,535179020,20,RL,80.0,10032,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,NAmes,Norm,Norm,1Fam,1Story,6,5,1959,1959,Gable,CompShg,Wd Sdng,Wd Sdng,Stone,432.0,TA,TA,CBlock,TA,TA,No,Rec,734.0,Unf,0.0,510.0,1244.0,GasA,Ex,Y,SBrkr,1580,0,0,1580,1.0,0.0,1,1,3,1,TA,6,Typ,2,Gd,Attchd,1956.0,Unf,2.0,440.0,TA,TA,Y,0,28,0,0,160,0,NaN,GdWo,NaN,0,6,2010,WD,Normal,159500
1282,1283,535477090,20,RL,69.0,7590,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,NAmes,PosN,Norm,1Fam,1Story,5,5,1963,1963,Gable,CompShg,Wd Sdng,Wd Sdng,None,0.0,TA,TA,CBlock,TA,TA,No,Unf,0.0,Unf,0.0,1117.0,1117.0,GasA,Ex,Y,SBrkr,1117,0,0,1117,0.0,0.0,1,0,3,1,TA,6,Typ,0,NaN,Attchd,1963.0,Unf,1.0,264.0,TA,TA,Y,0,0,0,0,0,0,NaN,NaN,NaN,0,5,2008,COD,Normal,136870
971,972,923203110,120,RM,32.0,4500,Pave,NaN,Reg,Lvl,AllPub,FR2,Gtl,Mitchel,Norm,Norm,TwnhsE,1Story,6,5,1998,1998,Hip,CompShg,VinylSd,VinylSd,BrkFace,320.0,TA,TA,PConc,Ex,TA,No,GLQ,866.0,Unf,0.0,338.0,1204.0,GasA,Ex,Y,SBrkr,1204,0,0,1204,1.0,0.0,2,0,2,1,TA,5,Typ,0,NaN,Attchd,1998.0,Fin,2.0,412.0,TA,TA,Y,0,247,0,0,0,0,NaN,NaN,NaN,0,6,2009,WD,Normal,162000
1230,1231,535105030,20,RL,75.0,7875,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,NAmes,Norm,Norm,1Fam,1Story,5,6,1961,1961,Gable,CompShg,VinylSd,VinylSd,BrkFace,136.0,TA,TA,CBlock,TA,TA,No,Rec,572.0,Unf,0.0,572.0,1144.0,GasA,Gd,Y,SBrkr,1144,0,0,1144,1.0,0.0,1,0,3,1,TA,6,Typ,0,NaN,Attchd,1961.0,Unf,2.0,456.0,TA,TA,Y,0,0,0,0,0,0,NaN,GdWo,NaN,0,9,2008,WD,Normal,139950

In [545]:
# Supression dees cols inutiles : 82 - 6 : 76

df = df.drop(['Order',
              'PID',
              'Alley',
              'Pool QC', 
              'Fence', 
              "Misc Feature"], axis=1)

In [546]:
# set the max columns to none
pd.set_option('display.max_columns', None)

In [547]:
df.isna().sum(axis=0)

MS SubClass         0
MS Zoning           0
Lot Frontage      490
Lot Area            0
Street              0
                 ...
Mo Sold             0
Yr Sold             0
Sale Type           0
Sale Condition      0
SalePrice           0
Length: 76, dtype: int64

In [548]:
#pourcentage de valeurs manquantes dans chaque variable

df_nan = df.isnull().sum()/len(df)*100
df_nan

MS SubClass        0.000000
MS Zoning          0.000000
Lot Frontage      16.723549
Lot Area           0.000000
Street             0.000000
                    ...
Mo Sold            0.000000
Yr Sold            0.000000
Sale Type          0.000000
Sale Condition     0.000000
SalePrice          0.000000
Length: 76, dtype: float64

In [549]:
#Supression des colonnes contenant des NaN superieur à 3 chiffres : 76 - 1 : 75

for col in df.columns:
    if df[col].isna().sum()/len(df) >= 0.3:
        df.drop(col, axis=1, inplace=True)
df.shape

(2930, 75)

In [550]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2930 entries, 0 to 2929
Data columns (total 75 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   MS SubClass      2930 non-null   int64
 1   MS Zoning        2930 non-null   object
 2   Lot Frontage     2440 non-null   float64
 3   Lot Area         2930 non-null   int64
 4   Street           2930 non-null   object
 5   Lot Shape        2930 non-null   object
 6   Land Contour     2930 non-null   object
 7   Utilities        2930 non-null   object
 8   Lot Config       2930 non-null   object
 9   Land Slope       2930 non-null   object
 10  Neighborhood     2930 non-null   object
 11  Condition 1      2930 non-null   object
 12  Condition 2      2930 non-null   object
 13  Bldg Type        2930 non-null   object
 14  House Style      2930 non-null   object
 15  Overall Qual     2930 non-null   int64
 16  Overall Cond     2930 non-null   int64
 17  Year Built       2930 non-null   int64
 18  Year Remod/Add   2930 non-null   int64
 19  Roof Style       2930 non-null   object
 20  Roof Matl        2930 non-null   object
 21  Exterior 1st     2930 non-null   object
 22  Exterior 2nd     2930 non-null   object
 23  Mas Vnr Type     2907 non-null   object
 24  Mas Vnr Area     2907 non-null   float64
 25  Exter Qual       2930 non-null   object
 26  Exter Cond       2930 non-null   object
 27  Foundation       2930 non-null   object
 28  Bsmt Qual        2850 non-null   object
 29  Bsmt Cond        2850 non-null   object
 30  Bsmt Exposure    2847 non-null   object
 31  BsmtFin Type 1   2850 non-null   object
 32  BsmtFin SF 1     2929 non-null   float64
 33  BsmtFin Type 2   2849 non-null   object
 34  BsmtFin SF 2     2929 non-null   float64
 35  Bsmt Unf SF      2929 non-null   float64
 36  Total Bsmt SF    2929 non-null   float64
 37  Heating          2930 non-null   object
 38  Heating QC       2930 non-null   object
 39  Central Air      2930 non-null   object
 40  Electrical       2929 non-null   object
 41  1st Flr SF       2930 non-null   int64
 42  2nd Flr SF       2930 non-null   int64
 43  Low Qual Fin SF  2930 non-null   int64
 44  Gr Liv Area      2930 non-null   int64
 45  Bsmt Full Bath   2928 non-null   float64
 46  Bsmt Half Bath   2928 non-null   float64
 47  Full Bath        2930 non-null   int64
 48  Half Bath        2930 non-null   int64
 49  Bedroom AbvGr    2930 non-null   int64
 50  Kitchen AbvGr    2930 non-null   int64
 51  Kitchen Qual     2930 non-null   object
 52  TotRms AbvGrd    2930 non-null   int64
 53  Functional       2930 non-null   object
 54  Fireplaces       2930 non-null   int64
 55  Garage Type      2773 non-null   object
 56  Garage Yr Blt    2771 non-null   float64
 57  Garage Finish    2771 non-null   object
 58  Garage Cars      2929 non-null   float64
 59  Garage Area      2929 non-null   float64
 60  Garage Qual      2771 non-null   object
 61  Garage Cond      2771 non-null   object
 62  Paved Drive      2930 non-null   object
 63  Wood Deck SF     2930 non-null   int64
 64  Open Porch SF    2930 non-null   int64
 65  Enclosed Porch   2930 non-null   int64
 66  3Ssn Porch       2930 non-null   int64
 67  Screen Porch     2930 non-null   int64
 68  Pool Area        2930 non-null   int64
 69  Misc Val         2930 non-null   int64
 70  Mo Sold          2930 non-null   int64
 71  Yr Sold          2930 non-null   int64
 72  Sale Type        2930 non-null   object
 73  Sale Condition   2930 non-null   object
 74  SalePrice        2930 non-null   int64
dtypes: float64(11), int64(26), object(38)
memory usage: 1.7+ MB

In [551]:
df.describe()

,MS SubClass,Lot Frontage,Lot Area,Overall Qual,Overall Cond,Year Built,Year Remod/Add,Mas Vnr Area,BsmtFin SF 1,BsmtFin SF 2,Bsmt Unf SF,Total Bsmt SF,1st Flr SF,2nd Flr SF,Low Qual Fin SF,Gr Liv Area,Bsmt Full Bath,Bsmt Half Bath,Full Bath,Half Bath,Bedroom AbvGr,Kitchen AbvGr,TotRms AbvGrd,Fireplaces,Garage Yr Blt,Garage Cars,Garage Area,Wood Deck SF,Open Porch SF,Enclosed Porch,3Ssn Porch,Screen Porch,Pool Area,Misc Val,Mo Sold,Yr Sold,SalePrice
count,2930.000000,2440.000000,2930.000000,2930.000000,2930.000000,2930.000000,2930.000000,2907.000000,2929.000000,2929.000000,2929.000000,2929.000000,2930.000000,2930.000000,2930.000000,2930.000000,2928.000000,2928.000000,2930.000000,2930.000000,2930.000000,2930.000000,2930.000000,2930.000000,2771.000000,2929.000000,2929.000000,2930.000000,2930.000000,2930.000000,2930.000000,2930.000000,2930.000000,2930.000000,2930.000000,2930.000000,2930.000000
mean,57.387372,69.224590,10147.921843,6.094881,5.563140,1971.356314,1984.266553,101.896801,442.629566,49.722431,559.262547,1051.614544,1159.557679,335.455973,4.676792,1499.690444,0.431352,0.061134,1.566553,0.379522,2.854266,1.044369,6.443003,0.599317,1978.132443,1.766815,472.819734,93.751877,47.533447,23.011604,2.592491,16.002048,2.243345,50.635154,6.216041,2007.790444,180796.060068
std,42.638025,23.365335,7880.017759,1.411026,1.111537,30.245361,20.860286,179.112611,455.590839,169.168476,439.494153,440.615067,391.890885,428.395715,46.310510,505.508887,0.524820,0.245254,0.552941,0.502629,0.827731,0.214076,1.572964,0.647921,25.528411,0.760566,215.046549,126.361562,67.483400,64.139059,25.141331,56.087370,35.597181,566.344288,2.714492,1.316613,79886.692357
min,20.000000,21.000000,1300.000000,1.000000,1.000000,1872.000000,1950.000000,0.000000,0.000000,0.000000,0.000000,0.000000,334.000000,0.000000,0.000000,334.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,0.000000,1895.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,2006.000000,12789.000000
25%,20.000000,58.000000,7440.250000,5.000000,5.000000,1954.000000,1965.000000,0.000000,0.000000,0.000000,219.000000,793.000000,876.250000,0.000000,0.000000,1126.000000,0.000000,0.000000,1.000000,0.000000,2.000000,1.000000,5.000000,0.000000,1960.000000,1.000000,320.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,4.000000,2007.000000,129500.000000
50%,50.000000,68.000000,9436.500000,6.000000,5.000000,1973.000000,1993.000000,0.000000,370.000000,0.000000,466.000000,990.000000,1084.000000,0.000000,0.000000,1442.000000,0.000000,0.000000,2.000000,0.000000,3.000000,1.000000,6.000000,1.000000,1979.000000,2.000000,480.000000,0.000000,27.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.000000,2008.000000,160000.000000
75%,70.000000,80.000000,11555.250000,7.000000,6.000000,2001.000000,2004.000000,164.000000,734.000000,0.000000,802.000000,1302.000000,1384.000000,703.750000,0.000000,1742.750000,1.000000,0.000000,2.000000,1.000000,3.000000,1.000000,7.000000,1.000000,2002.000000,2.000000,576.000000,168.000000,70.000000,0.000000,0.000000,0.000000,0.000000,0.000000,8.000000,2009.000000,213500.000000
max,190.000000,313.000000,215245.000000,10.000000,9.000000,2010.000000,2010.000000,1600.000000,5644.000000,1526.000000,2336.000000,6110.000000,5095.000000,2065.000000,1064.000000,5642.000000,3.000000,2.000000,4.000000,2.000000,8.000000,3.000000,15.000000,4.000000,2207.000000,5.000000,1488.000000,1424.000000,742.000000,1012.000000,508.000000,576.000000,800.000000,17000.000000,12.000000,2010.000000,755000.000000

# 1.2. Creation de nouvelle variable

In [552]:
#Défini une note à chaque categorie
dict_a = {'Ex': 10, 'Gd': 8, 'TA': 6, 'Fa':4, 'Po':2}
dict_b = {'Ex': 10, 'Gd': 8, 'TA': 6, 'Fa':4, 'Po':2, 'NA':0}
dict_c = {'Gd': 8, 'Av': 6, 'Mn':4, 'No':2, 'NA':0}

### 1. TOTAL Bath (FulBath + HalfBath) NUM

In [553]:
# TOTAL Bath (FulBath + HalfBath) NUM

df["TotalFullBath"] = df["Bsmt Full Bath"] + df["Full Bath"]
df["TotalHalfBath"] = df["Bsmt Half Bath"] + df["Half Bath"]
df["Total Bath"] = (df["TotalHalfBath"]/2) + df["TotalFullBath"]

### 2. Overall (Classement de la qualité, Évalue l'état général de la maison, des materriaux et la finition) NUM

In [554]:
# Overall (Classement de la qualité Évalue l'état général de la maison, des materriaux et la finition) NUM

df["Overall"] = df["Overall Cond"] + df["Overall Qual"]

###  3. Exter (Classement de la qualité Évalue l'état général de la maison, des materriaux et la finition) NUM

In [555]:
# Exter (Classement de la qualité Évalue l'état général de l'exterieur, des materiaux et la finition) NUM

#Défini une note à chaque categorie
df["Exter Qual"] = df["Exter Qual"].apply(lambda x: dict_a.get(x))
df["Exter Cond"] = df["Exter Cond"].apply(lambda x: dict_a.get(x))

df["Exter"] = df["Exter Qual"] + df["Exter Cond"]

### 4. Garage (Evalue la Qualité et l'etat du garage)

In [556]:
# Garage (Evalue la Qualité et l'etat du garage)

#Défini une note à chaque categorie
df["Garage Cond"] = df["Garage Cond"].apply(lambda x: dict_b.get(x))
df["Garage Qual"] = df["Garage Qual"].apply(lambda x: dict_b.get(x))

df["Garage"] = df["Garage Qual"] + df["Garage Cond"]

### 5. Surface_plus (Prend en compte les m2 des surfaces du garage + sous sol)

In [557]:
# Surface_plus (Prend en compte les m2 des surfaces du garage + sous sol)

df["Surface_sup"] = df["Garage Area"] + df["Total Bsmt SF"]

### 6. Renovation (Nombre d'année depuis la derrnière renovation)

In [559]:
df['Renovation'] = 2022 - df['Year Remod/Add']

### 7. Surface_plus_ext (Prend en compte les m2 des surfaces de la veranda + porch fermé)

In [560]:
### Surface_plus_ext (Prend en compte les m2 des surfaces de la veranda + porch fermé)

df["Surface_sup_ext"] = df["Enclosed Porch"] + df["Screen Porch"]

### 8. Bsmt (Condition et Qualité du sous sol + l'exposition du bati)

In [561]:
#Bsmt (Condition et Qualité du sous sol)

df["Bsmt Cond"] = df["Bsmt Cond"].apply(lambda x: dict_b.get(x))
df["Bsmt Qual"] = df["Bsmt Qual"].apply(lambda x: dict_b.get(x))

In [562]:
df["Bsmt Exposure"] = df["Bsmt Exposure"].apply(lambda x: dict_c.get(x))

In [563]:
df["Bsmt"] = df["Bsmt Cond"] + df["Bsmt Qual"] + df["Bsmt Exposure"]

### 9. Saleprice_quartier (Prix du m2 par quartier )

In [564]:
#Saleprice_quartier (Prix du m2 par quartier )

df["SalePrice_m2"] = df["SalePrice"] / df["Gr Liv Area"]
df["SalePrice_m2"]

0       129.830918
1       117.187500
2       129.420617
3       115.639810
4       116.574586
           ...
2925    142.073779
2926    145.232816
2927    136.082474
2928    122.390209
2929     94.000000
Name: SalePrice_m2, Length: 2930, dtype: float64

In [565]:
SalePrice_m2_quartier = df[['Neighborhood','SalePrice_m2']]
SalePrice_m2_quartier

     Neighborhood  SalePrice_m2
0           NAmes    129.830918
1           NAmes    117.187500
2           NAmes    129.420617
3           NAmes    115.639810
4         Gilbert    116.574586
...           ...           ...
2925      Mitchel    142.073779
2926      Mitchel    145.232816
2927      Mitchel    136.082474
2928      Mitchel    122.390209
2929      Mitchel     94.000000

[2930 rows x 2 columns]

In [566]:

SalePrice_m2_quartier.groupby(df['Neighborhood']).median().round(2)

              SalePrice_m2
Neighborhood
Blmngtn             139.83
Blueste             112.18
BrDale               94.81
BrkSide             100.57
ClearCr             118.58
CollgCr             135.40
Crawfor             117.51
Edwards             102.01
Gilbert             117.48
Greens              170.27
GrnHill             198.66
IDOTRR               87.25
Landmrk             103.79
MeadowV              86.10
Mitchel             134.26
NAmes               119.55
NPkVill             111.20
NWAmes              114.91
NoRidge             129.38
NridgHt             160.36
OldTown              92.53
SWISU                84.59
Sawyer              124.52
SawyerW             115.75
Somerst             140.53
StoneBr             157.86
Timber              141.82
Veenker             137.72

In [567]:
Saleprice_m2_dic = {
'Blmngtn' : 139.83,
'Blueste' : 112.18,
'BrDale'  : 94.81,
'BrkSide' : 100.57,
'ClearCr' : 118.58,
'CollgCr' : 135.40,
'Crawfor' : 117.51,
'Edwards' : 102.01,
'Gilbert' : 117.48,
'Greens'  : 170.27,
'GrnHill' : 198.66,
'IDOTRR'  : 87.25,
'Landmrk' : 103.79,
'MeadowV' : 86.10,
'Mitchel' : 134.26,
'NAmes'   : 119.55,
'NPkVill' : 111.20,
'NWAmes'  : 114.91,
'NoRidge' : 129.38,
'NridgHt' : 160.36,
'OldTown' : 92.53,
'SWISU'   : 84.59,
'Sawyer'  : 124.52,
'SawyerW' : 115.75,
'Somerst' : 140.53,
'StoneBr' : 157.86,
'Timber'  : 141.82,
'Veenker' : 137.72
}

In [568]:
df_1 = pd.DataFrame(list(Saleprice_m2_dic.items()),
                   columns=['Neighborhood', 'Saleprice_m2_quartier'])

In [569]:
df_1

   Neighborhood  Saleprice_m2_quartier
0       Blmngtn                 139.83
1       Blueste                 112.18
2        BrDale                  94.81
3       BrkSide                 100.57
4       ClearCr                 118.58
5       CollgCr                 135.40
6       Crawfor                 117.51
7       Edwards                 102.01
8       Gilbert                 117.48
9        Greens                 170.27
10      GrnHill                 198.66
11       IDOTRR                  87.25
12      Landmrk                 103.79
13      MeadowV                  86.10
14      Mitchel                 134.26
15        NAmes                 119.55
16      NPkVill                 111.20
17       NWAmes                 114.91
18      NoRidge                 129.38
19      NridgHt                 160.36
20      OldTown                  92.53
21        SWISU                  84.59
22       Sawyer                 124.52
23      SawyerW                 115.75
24      Somerst                 140.53
25      StoneBr                 157.86
26       Timber                 141.82
27      Veenker                 137.72

In [570]:
dico=dict(zip(list(df_1['Neighborhood']),list(df_1['Saleprice_m2_quartier'])))

In [571]:
df['Saleprice_m2_quartier'] = df['Neighborhood'].map(Saleprice_m2_dic)

### 10. Saleprice_med_quartier (Prix median par quartier )

In [572]:
#Saleprice_med_quartier (Prix median par quartier )

df_SalePrice_med_quartier = df[['Neighborhood','SalePrice']]
df_SalePrice_med_quartier

     Neighborhood  SalePrice
0           NAmes     215000
1           NAmes     105000
2           NAmes     172000
3           NAmes     244000
4         Gilbert     189900
...           ...        ...
2925      Mitchel     142500
2926      Mitchel     131000
2927      Mitchel     132000
2928      Mitchel     170000
2929      Mitchel     188000

[2930 rows x 2 columns]

In [573]:
round(df_SalePrice_med_quartier.groupby(df['Neighborhood']).median())

              SalePrice
Neighborhood
Blmngtn        191500.0
Blueste        130500.0
BrDale         106000.0
BrkSide        126750.0
ClearCr        197500.0
CollgCr        200000.0
Crawfor        200624.0
Edwards        125000.0
Gilbert        183000.0
Greens         198000.0
GrnHill        280000.0
IDOTRR         106500.0
Landmrk        137000.0
MeadowV         88250.0
Mitchel        153500.0
NAmes          140000.0
NPkVill        143750.0
NWAmes         181000.0
NoRidge        302000.0
NridgHt        317750.0
OldTown        119900.0
SWISU          136200.0
Sawyer         135000.0
SawyerW        180000.0
Somerst        225500.0
StoneBr        319000.0
Timber         232106.0
Veenker        250250.0

In [574]:
Saleprice_med_dic = {
'Blmngtn': 191500.0,
'Blueste': 130500.0,
'BrDale': 106000.0,
'BrkSide': 126750.0,
'ClearCr'	: 197500.0,
'CollgCr'	: 200000.0,
'Crawfor'	: 200624.0,
'Edwards'	: 125000.0,
'Gilbert'	: 183000.0,
'Greens'	: 198000.0,
'GrnHill'	: 280000.0,
'IDOTRR'	: 106500.0,
'Landmrk': 137000.0,
'MeadowV': 88250.0,
'Mitchel'	: 153500.0,
'NAmes'	: 140000.0,
'NPkVill'	: 143750.0,
'NWAmes'	: 181000.0,
'NoRidge'	: 302000.0,
'NridgHt'	: 317750.0,
'OldTown'	: 119900.0,
'SWISU'	: 136200.0,
'Sawyer'	: 135000.0,
'SawyerW': 180000.0,
'Somerst'	: 225500.0,
'StoneBr'	: 319000.0,
'Timber'	: 232106.5,
'Veenker'	: 250250.0
}

In [575]:
df_2 = pd.DataFrame(list(Saleprice_med_dic.items()),
                   columns=['Neighborhood', 'Saleprice_med_quartier'])

df_2

   Neighborhood  Saleprice_med_quartier
0       Blmngtn                191500.0
1       Blueste                130500.0
2        BrDale                106000.0
3       BrkSide                126750.0
4       ClearCr                197500.0
5       CollgCr                200000.0
6       Crawfor                200624.0
7       Edwards                125000.0
8       Gilbert                183000.0
9        Greens                198000.0
10      GrnHill                280000.0
11       IDOTRR                106500.0
12      Landmrk                137000.0
13      MeadowV                 88250.0
14      Mitchel                153500.0
15        NAmes                140000.0
16      NPkVill                143750.0
17       NWAmes                181000.0
18      NoRidge                302000.0
19      NridgHt                317750.0
20      OldTown                119900.0
21        SWISU                136200.0
22       Sawyer                135000.0
23      SawyerW                180000.0
24      Somerst                225500.0
25      StoneBr                319000.0
26       Timber                232106.5
27      Veenker                250250.0

In [576]:
dico_2=dict(zip(list(df_2['Neighborhood']),list(df_2['Saleprice_med_quartier'])))

In [577]:
dico_2

{'Blmngtn': 191500.0,
 'Blueste': 130500.0,
 'BrDale': 106000.0,
 'BrkSide': 126750.0,
 'ClearCr': 197500.0,
 'CollgCr': 200000.0,
 'Crawfor': 200624.0,
 'Edwards': 125000.0,
 'Gilbert': 183000.0,
 'Greens': 198000.0,
 'GrnHill': 280000.0,
 'IDOTRR': 106500.0,
 'Landmrk': 137000.0,
 'MeadowV': 88250.0,
 'Mitchel': 153500.0,
 'NAmes': 140000.0,
 'NPkVill': 143750.0,
 'NWAmes': 181000.0,
 'NoRidge': 302000.0,
 'NridgHt': 317750.0,
 'OldTown': 119900.0,
 'SWISU': 136200.0,
 'Sawyer': 135000.0,
 'SawyerW': 180000.0,
 'Somerst': 225500.0,
 'StoneBr': 319000.0,
 'Timber': 232106.5,
 'Veenker': 250250.0}

In [578]:
#Saleprice_quartier (Prix du m2 par quartier )

df_SalePrice_mean_quartier = df[['Neighborhood','SalePrice']]
df_SalePrice_mean_quartier

     Neighborhood  SalePrice
0           NAmes     215000
1           NAmes     105000
2           NAmes     172000
3           NAmes     244000
4         Gilbert     189900
...           ...        ...
2925      Mitchel     142500
2926      Mitchel     131000
2927      Mitchel     132000
2928      Mitchel     170000
2929      Mitchel     188000

[2930 rows x 2 columns]

### 10bis. Saleprice_med_quartier (Prix median par quartier )

In [580]:
round(df_SalePrice_mean_quartier.groupby(df['Neighborhood']).mean())

              SalePrice
Neighborhood
Blmngtn        196662.0
Blueste        143590.0
BrDale         105608.0
BrkSide        124756.0
ClearCr        208662.0
CollgCr        201803.0
Crawfor        207551.0
Edwards        130843.0
Gilbert        190647.0
Greens         193531.0
GrnHill        280000.0
IDOTRR         103753.0
Landmrk        137000.0
MeadowV         95756.0
Mitchel        162227.0
NAmes          145097.0
NPkVill        140711.0
NWAmes         188407.0
NoRidge        330319.0
NridgHt        322018.0
OldTown        123992.0
SWISU          135072.0
Sawyer         136751.0
SawyerW        184070.0
Somerst        229707.0
StoneBr        324229.0
Timber         246600.0
Veenker        248315.0

In [581]:
Saleprice_mean_dic = {
'Blmngtn' :	196662,
'Blueste' :	143590,
'BrDale' :	105608,
'BrkSide' :	124756,
'ClearCr' :	208662,
'CollgCr' :	201803,
'Crawfor' :	207551,
'Edwards' :	130843,
'Gilbert' :	190647,
'Greens' :	193531,
'GrnHill' :	280000,
'IDOTRR' :	103753,
'Landmrk' :	137000,
'MeadowV' :	95756,
'Mitchel' :	162227,
'NAmes' :	145097,
'NPkVill' :	140711,
'NWAmes' :	188407,
'NoRidge' :	330319,
'NridgHt' :	322018,
'OldTown' :	123992,
'SWISU' :	135072,
'Sawyer' :	136751,
'SawyerW' :	184070,
'Somerst' :	229708,
'StoneBr' :	324229,
'Timber' :	246600,
'Veenker' :	248315
}

In [582]:
df_3 = pd.DataFrame(list(Saleprice_mean_dic.items()),
                   columns=['Neighborhood', 'Saleprice_mean_quartier'])

In [583]:
df_3

   Neighborhood  Saleprice_mean_quartier
0       Blmngtn                   196662
1       Blueste                   143590
2        BrDale                   105608
3       BrkSide                   124756
4       ClearCr                   208662
5       CollgCr                   201803
6       Crawfor                   207551
7       Edwards                   130843
8       Gilbert                   190647
9        Greens                   193531
10      GrnHill                   280000
11       IDOTRR                   103753
12      Landmrk                   137000
13      MeadowV                    95756
14      Mitchel                   162227
15        NAmes                   145097
16      NPkVill                   140711
17       NWAmes                   188407
18      NoRidge                   330319
19      NridgHt                   322018
20      OldTown                   123992
21        SWISU                   135072
22       Sawyer                   136751
23      SawyerW                   184070
24      Somerst                   229708
25      StoneBr                   324229
26       Timber                   246600
27      Veenker                   248315

# Merge du df1, df2 et df3 (colonne Saleprice_m2)

In [584]:
df

,MS SubClass,MS Zoning,Lot Frontage,Lot Area,Street,Lot Shape,Land Contour,Utilities,Lot Config,Land Slope,Neighborhood,Condition 1,Condition 2,Bldg Type,House Style,Overall Qual,Overall Cond,Year Built,Year Remod/Add,Roof Style,Roof Matl,Exterior 1st,Exterior 2nd,Mas Vnr Type,Mas Vnr Area,Exter Qual,Exter Cond,Foundation,Bsmt Qual,Bsmt Cond,Bsmt Exposure,BsmtFin Type 1,BsmtFin SF 1,BsmtFin Type 2,BsmtFin SF 2,Bsmt Unf SF,Total Bsmt SF,Heating,Heating QC,Central Air,Electrical,1st Flr SF,2nd Flr SF,Low Qual Fin SF,Gr Liv Area,Bsmt Full Bath,Bsmt Half Bath,Full Bath,Half Bath,Bedroom AbvGr,Kitchen AbvGr,Kitchen Qual,TotRms AbvGrd,Functional,Fireplaces,Garage Type,Garage Yr Blt,Garage Finish,Garage Cars,Garage Area,Garage Qual,Garage Cond,Paved Drive,Wood Deck SF,Open Porch SF,Enclosed Porch,3Ssn Porch,Screen Porch,Pool Area,Misc Val,Mo Sold,Yr Sold,Sale Type,Sale Condition,SalePrice,TotalFullBath,TotalHalfBath,Total Bath,Overall,Exter,Garage,Surface_sup,Renovation,Surface_sup_ext,Bsmt,SalePrice_m2,Saleprice_m2_quartier
0,20,RL,141.0,31770,Pave,IR1,Lvl,AllPub,Corner,Gtl,NAmes,Norm,Norm,1Fam,1Story,6,5,1960,1960,Hip,CompShg,BrkFace,Plywood,Stone,112.0,6,6,CBlock,6.0,8.0,8.0,BLQ,639.0,Unf,0.0,441.0,1080.0,GasA,Fa,Y,SBrkr,1656,0,0,1656,1.0,0.0,1,0,3,1,TA,7,Typ,2,Attchd,1960.0,Fin,2.0,528.0,6.0,6.0,P,210,62,0,0,0,0,0,5,2010,WD,Normal,215000,2.0,0.0,2.0,11,12,12.0,1608.0,62,0,22.0,129.830918,119.55
1,20,RH,80.0,11622,Pave,Reg,Lvl,AllPub,Inside,Gtl,NAmes,Feedr,Norm,1Fam,1Story,5,6,1961,1961,Gable,CompShg,VinylSd,VinylSd,None,0.0,6,6,CBlock,6.0,6.0,2.0,Rec,468.0,LwQ,144.0,270.0,882.0,GasA,TA,Y,SBrkr,896,0,0,896,0.0,0.0,1,0,2,1,TA,5,Typ,0,Attchd,1961.0,Unf,1.0,730.0,6.0,6.0,Y,140,0,0,0,120,0,0,6,2010,WD,Normal,105000,1.0,0.0,1.0,11,12,12.0,1612.0,61,120,14.0,117.187500,119.55
2,20,RL,81.0,14267,Pave,IR1,Lvl,AllPub,Corner,Gtl,NAmes,Norm,Norm,1Fam,1Story,6,6,1958,1958,Hip,CompShg,Wd Sdng,Wd Sdng,BrkFace,108.0,6,6,CBlock,6.0,6.0,2.0,ALQ,923.0,Unf,0.0,406.0,1329.0,GasA,TA,Y,SBrkr,1329,0,0,1329,0.0,0.0,1,1,3,1,Gd,6,Typ,0,Attchd,1958.0,Unf,1.0,312.0,6.0,6.0,Y,393,36,0,0,0,0,12500,6,2010,WD,Normal,172000,1.0,1.0,1.5,12,12,12.0,1641.0,64,0,14.0,129.420617,119.55
3,20,RL,93.0,11160,Pave,Reg,Lvl,AllPub,Corner,Gtl,NAmes,Norm,Norm,1Fam,1Story,7,5,1968,1968,Hip,CompShg,BrkFace,BrkFace,None,0.0,8,6,CBlock,6.0,6.0,2.0,ALQ,1065.0,Unf,0.0,1045.0,2110.0,GasA,Ex,Y,SBrkr,2110,0,0,2110,1.0,0.0,2,1,3,1,Ex,8,Typ,2,Attchd,1968.0,Fin,2.0,522.0,6.0,6.0,Y,0,0,0,0,0,0,0,4,2010,WD,Normal,244000,3.0,1.0,3.5,12,14,12.0,2632.0,54,0,14.0,115.639810,119.55
4,60,RL,74.0,13830,Pave,IR1,Lvl,AllPub,Inside,Gtl,Gilbert,Norm,Norm,1Fam,2Story,5,5,1997,1998,Gable,CompShg,VinylSd,VinylSd,None,0.0,6,6,PConc,8.0,6.0,2.0,GLQ,791.0,Unf,0.0,137.0,928.0,GasA,Gd,Y,SBrkr,928,701,0,1629,0.0,0.0,2,1,3,1,TA,6,Typ,1,Attchd,1997.0,Fin,2.0,482.0,6.0,6.0,Y,212,34,0,0,0,0,0,3,2010,WD,Normal,189900,2.0,1.0,2.5,10,12,12.0,1410.0,24,0,16.0,116.574586,117.48
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2925,80,RL,37.0,7937,Pave,IR1,Lvl,AllPub,CulDSac,Gtl,Mitchel,Norm,Norm,1Fam,SLvl,6,6,1984,1984,Gable,CompShg,HdBoard,HdBoard,None,0.0,6,6,CBlock,6.0,6.0,6.0,GLQ,819.0,Unf,0.0,184.0,1003.0,GasA,TA,Y,SBrkr,1003,0,0,1003,1.0,0.0,1,0,3,1,TA,6,Typ,0,Detchd,1984.0,Unf,2.0,588.0,6.0,6.0,Y,120,0,0,0,0,0,0,3,2006,WD,Normal,142500,2.0,0.0,2.0,12,12,12.0,1591.0,38,0,18.0,142.073779,134.26
2926,20,RL,NaN,8885,Pave,IR1,Low,AllPub,Inside,Mod,Mitchel,Norm,Norm,1Fam,1Story,5,5,1983,1983,Gable,CompShg,HdBoard,HdBoard,None,0.0,6,6,CBlock,8.0,6.0,6.0,BLQ,301.0,ALQ,324.0,239.0,864.0,GasA,TA,Y,SBrkr,902,0,0,902,1.0,0.0,1,0,2,1,TA,5,Typ,0,Attchd,1983.0,Unf,2.0,484.0,6.0,6.0,Y,164,0,0,0,0,0,0,6,2006,WD,Normal,131000,2.0,0.0,2.0,10,12,12.0,1348.0,39,0,20.0,145.232816,134.26
2927,85,RL,62.0,10441,Pave,Reg,Lvl,AllPub,Inside,Gtl,Mitchel,Norm,Norm,1Fam,SFoyer,5,5,1992,1992,Gable,CompShg,HdBoard,Wd Shng,None,0.0,6,6,PConc,8.0,6.0,6.0,GLQ,337.0,Unf,0.0,575.0,912.0,GasA,TA,Y,SBrkr,970,0,0,970,0.0,1.0,1,0,3,1,TA,6,Typ,0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,Y,80,32,0,0,0,0,700,7,2006,WD,Normal,132000,1.0,1.0,1.5,10,12,NaN,912.0,30,0,20.0,136.082474,134.26
2928,20,RL,77.0,10010,Pave,Reg,Lvl,AllPub,Inside,Mod,Mitchel,Norm,Norm,1Fam,1Story,5,5,1974,1975,Gable,CompShg,HdBoard,HdBoard,None,0.0,6,6,CBlock,8.0,6.0,6.0,ALQ,1071.0,LwQ,123.0,195.0,1389.0,GasA,Gd,Y,SBrkr,1389,0,0,1389,1.0,0.0,1,0,2,1,TA,6,Typ,1,Attchd,1975.0,RFn,2.0,418.0,6.0,6.0,Y,240,38,0,0,0,0,0,4,2006,WD,Normal,170000,2.0,0.0,2.0,10,12,12.0,1807.0,47,0,20.0,122.390209,134.26
2929,60,RL,74.0,9627,Pave,Reg,Lvl,AllPub,Inside,Mod,Mitchel,Norm,Norm,1Fam,2Story,7,5,1993,1994,Gable,CompShg,HdBoard,HdBoard,BrkFace,94.0,6,6,PConc,8.0,6.0,6.0,LwQ,758.0,Unf,0.0,238.0,996.0,GasA,Ex,Y,SBrkr,996,1004,0,2000,0.0,0.0,2,1,3,1,TA,9,Typ,1,Attchd,1993.0,Fin,3.0,650.0,6.0,6.0,Y,190,48,0,0,0,0,0,11,2006,WD,Normal,188000,2.0,1.0,2.5,12,12,12.0,1646.0,28,0,20.0,94.000000,134.26

In [585]:
df = df.merge(df_2, how='inner', on='Neighborhood')

In [586]:
df

,MS SubClass,MS Zoning,Lot Frontage,Lot Area,Street,Lot Shape,Land Contour,Utilities,Lot Config,Land Slope,Neighborhood,Condition 1,Condition 2,Bldg Type,House Style,Overall Qual,Overall Cond,Year Built,Year Remod/Add,Roof Style,Roof Matl,Exterior 1st,Exterior 2nd,Mas Vnr Type,Mas Vnr Area,Exter Qual,Exter Cond,Foundation,Bsmt Qual,Bsmt Cond,Bsmt Exposure,BsmtFin Type 1,BsmtFin SF 1,BsmtFin Type 2,BsmtFin SF 2,Bsmt Unf SF,Total Bsmt SF,Heating,Heating QC,Central Air,Electrical,1st Flr SF,2nd Flr SF,Low Qual Fin SF,Gr Liv Area,Bsmt Full Bath,Bsmt Half Bath,Full Bath,Half Bath,Bedroom AbvGr,Kitchen AbvGr,Kitchen Qual,TotRms AbvGrd,Functional,Fireplaces,Garage Type,Garage Yr Blt,Garage Finish,Garage Cars,Garage Area,Garage Qual,Garage Cond,Paved Drive,Wood Deck SF,Open Porch SF,Enclosed Porch,3Ssn Porch,Screen Porch,Pool Area,Misc Val,Mo Sold,Yr Sold,Sale Type,Sale Condition,SalePrice,TotalFullBath,TotalHalfBath,Total Bath,Overall,Exter,Garage,Surface_sup,Renovation,Surface_sup_ext,Bsmt,SalePrice_m2,Saleprice_m2_quartier,Saleprice_med_quartier
0,20,RL,141.0,31770,Pave,IR1,Lvl,AllPub,Corner,Gtl,NAmes,Norm,Norm,1Fam,1Story,6,5,1960,1960,Hip,CompShg,BrkFace,Plywood,Stone,112.0,6,6,CBlock,6.0,8.0,8.0,BLQ,639.0,Unf,0.0,441.0,1080.0,GasA,Fa,Y,SBrkr,1656,0,0,1656,1.0,0.0,1,0,3,1,TA,7,Typ,2,Attchd,1960.0,Fin,2.0,528.0,6.0,6.0,P,210,62,0,0,0,0,0,5,2010,WD,Normal,215000,2.0,0.0,2.0,11,12,12.0,1608.0,62,0,22.0,129.830918,119.55,140000.0
1,20,RH,80.0,11622,Pave,Reg,Lvl,AllPub,Inside,Gtl,NAmes,Feedr,Norm,1Fam,1Story,5,6,1961,1961,Gable,CompShg,VinylSd,VinylSd,None,0.0,6,6,CBlock,6.0,6.0,2.0,Rec,468.0,LwQ,144.0,270.0,882.0,GasA,TA,Y,SBrkr,896,0,0,896,0.0,0.0,1,0,2,1,TA,5,Typ,0,Attchd,1961.0,Unf,1.0,730.0,6.0,6.0,Y,140,0,0,0,120,0,0,6,2010,WD,Normal,105000,1.0,0.0,1.0,11,12,12.0,1612.0,61,120,14.0,117.187500,119.55,140000.0
2,20,RL,81.0,14267,Pave,IR1,Lvl,AllPub,Corner,Gtl,NAmes,Norm,Norm,1Fam,1Story,6,6,1958,1958,Hip,CompShg,Wd Sdng,Wd Sdng,BrkFace,108.0,6,6,CBlock,6.0,6.0,2.0,ALQ,923.0,Unf,0.0,406.0,1329.0,GasA,TA,Y,SBrkr,1329,0,0,1329,0.0,0.0,1,1,3,1,Gd,6,Typ,0,Attchd,1958.0,Unf,1.0,312.0,6.0,6.0,Y,393,36,0,0,0,0,12500,6,2010,WD,Normal,172000,1.0,1.0,1.5,12,12,12.0,1641.0,64,0,14.0,129.420617,119.55,140000.0
3,20,RL,93.0,11160,Pave,Reg,Lvl,AllPub,Corner,Gtl,NAmes,Norm,Norm,1Fam,1Story,7,5,1968,1968,Hip,CompShg,BrkFace,BrkFace,None,0.0,8,6,CBlock,6.0,6.0,2.0,ALQ,1065.0,Unf,0.0,1045.0,2110.0,GasA,Ex,Y,SBrkr,2110,0,0,2110,1.0,0.0,2,1,3,1,Ex,8,Typ,2,Attchd,1968.0,Fin,2.0,522.0,6.0,6.0,Y,0,0,0,0,0,0,0,4,2010,WD,Normal,244000,3.0,1.0,3.5,12,14,12.0,2632.0,54,0,14.0,115.639810,119.55,140000.0
4,20,RL,NaN,11241,Pave,IR1,Lvl,AllPub,CulDSac,Gtl,NAmes,Norm,Norm,1Fam,1Story,6,7,1970,1970,Gable,CompShg,Wd Sdng,Wd Sdng,BrkFace,180.0,6,6,CBlock,6.0,6.0,2.0,ALQ,578.0,Unf,0.0,426.0,1004.0,GasA,Ex,Y,SBrkr,1004,0,0,1004,1.0,0.0,1,0,2,1,TA,5,Typ,1,Attchd,1970.0,Fin,2.0,480.0,6.0,6.0,Y,0,0,0,0,0,0,700,3,2010,WD,Normal,149000,2.0,0.0,2.0,13,12,12.0,1484.0,52,0,14.0,148.406375,119.55,140000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2925,20,RL,NaN,11250,Pave,IR1,Lvl,AllPub,Inside,Gtl,Veenker,Norm,Norm,1Fam,1Story,6,6,1977,1977,Gable,CompShg,Plywood,Plywood,None,0.0,8,6,CBlock,8.0,6.0,2.0,ALQ,767.0,Unf,0.0,441.0,1208.0,GasA,TA,Y,SBrkr,1208,0,0,1208,1.0,0.0,1,1,3,1,TA,6,Typ,1,Attchd,1977.0,RFn,2.0,546.0,6.0,6.0,Y,198,42,0,0,0,0,0,6,2006,WD,Normal,165000,2.0,1.0,2.5,12,14,12.0,1754.0,45,0,16.0,136.589404,137.72,250250.0
2926,20,RL,68.0,50271,Pave,IR1,Low,AllPub,Inside,Gtl,Veenker,Norm,Norm,1Fam,1Story,9,5,1981,1987,Gable,WdShngl,WdShing,Wd Shng,None,0.0,8,6,CBlock,10.0,6.0,8.0,GLQ,1810.0,Unf,0.0,32.0,1842.0,GasA,Gd,Y,SBrkr,1842,0,0,1842,2.0,0.0,0,1,0,1,Gd,5,Typ,1,Attchd,1981.0,Fin,3.0,894.0,6.0,6.0,Y,857,72,0,0,0,0,0,11,2006,WD,Normal,385000,2.0,1.0,2.5,14,14,12.0,2736.0,35,0,24.0,209.011944,137.72,250250.0
2927,120,RM,NaN,9763,Pave,IR1,Lvl,AllPub,Inside,Gtl,GrnHill,Norm,Norm,TwnhsE,1Story,7,5,1998,1998,Gable,CompShg,Wd Sdng,Wd Sdng,BrkFace,239.0,8,6,PConc,8.0,6.0,2.0,GLQ,1102.0,ALQ,72.0,328.0,1502.0,GasA,Ex,Y,SBrkr,1502,0,0,1502,1.0,0.0,1,1,1,1,Gd,5,Typ,1,Attchd,1998.0,Fin,1.0,286.0,6.0,6.0,Y,0,0,0,0,0,0,0,9,2007,WD,Normal,330000,2.0,1.0,2.5,12,14,12.0,1788.0,24,0,16.0,219.707057,198.66,280000.0
2928,120,RM,NaN,8239,Pave,IR1,Lvl,AllPub,Inside,Gtl,GrnHill,Norm,Norm,TwnhsE,1Story,7,5,1986,1986,Gable,CompShg,BrkFace,Wd Sdng,None,0.0,8,6,CBlock,NaN,NaN,NaN,NaN,0.0,NaN,0.0,0.0,0.0,GasA,Gd,Y,SBrkr,1295,0,0,1295,0.0,0.0,2,0,2,1,Gd,5,Typ,0,Attchd,1986.0,RFn,1.0,312.0,6.0,6.0,Y,0,0,0,0,0,0,0,11,2006,WD,Normal,230000,2.0,0.0,2.0,12,14,12.0,312.0,36,0,NaN,177.606178,198.66,280000.0
2929,160,RH,NaN,3612,Pave,IR1,Lvl,AllPub,Inside,Gtl,Landmrk,Norm,Norm,Twnhs,2Story,6,5,1993,1994,Gable,CompShg,VinylSd,VinylSd,None,0.0,6,6,PConc,8.0,6.0,2.0,GLQ,338.0,Unf,0.0,292.0,630.0,GasA,Ex,Y,SBrkr,630,690,0,1320,0.0,0.0,2,1,3,1,TA,5,Typ,0,Detchd,1993.0,Unf,2.0,484.0,6.0,6.0,Y,0,48,0,0,0,0,0,6,2006,WD,Normal,137000,2.0,1.0,2.5,11,12,12.0,1114.0,28,0,16.0,103.787879,103.79,137000.0

In [587]:
df = df.merge(df_3, how='inner', on='Neighborhood')

## 1.3. Enregistrement du dataframe contenant les nouvelles variables

In [588]:
df.to_csv("data/AmesHousing_clean.csv", index = False)